.TH "_sh_sha256_ctx" 3 "18 Nov 2014" "Version 2.16" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_sh_sha256_ctx \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned int \fBtot_len\fP"
.br
.ti -1c
.RI "unsigned int \fBlen\fP"
.br
.ti -1c
.RI "unsigned char \fBblock\fP [2 *(512/8)]"
.br
.ti -1c
.RI "uint32_t \fBh\fP [8]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 895 of file shmem.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
