.TH "Libshare_fsproc" 3 "20 Mar 2015" "Version 2.24" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Libshare_fsproc \- 
.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBshfs_app_name\fP (char *app_name)"
.br
.ti -1c
.RI "int \fBshfs_app_certify\fP (char *exec_path)"
.br
.ti -1c
.RI "int \fBshfs_proc_lock\fP (char *process_path, char *runtime_mode)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
