.TH "Libshare_fscache" 3 "20 Mar 2015" "Version 2.24" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Libshare_fscache \- 
.PP
File-system inode cacheing.  

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBshfs_ino_t\fP * \fBshfs_cache_get\fP (\fBshfs_ino_t\fP *parent, \fBshkey_t\fP *name)"
.br
.ti -1c
.RI "void \fBshfs_cache_set\fP (\fBshfs_ino_t\fP *parent, \fBshfs_ino_t\fP *inode)"
.br
.ti -1c
.RI "void \fBshfs_inode_cache_free\fP (\fBshfs_ino_t\fP *inode)"
.br
.in -1c
.SH "Detailed Description"
.PP 
File-system inode cacheing. 
.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
