.TH "Libshare_fshome" 3 "20 Mar 2015" "Version 2.24" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Libshare_fshome \- 
.PP
individual user 'home' file-system  

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBshfs_t\fP * \fBshfs_home_fs\fP (\fBshkey_t\fP *id_key)"
.br
.ti -1c
.RI "\fBshfs_ino_t\fP * \fBshfs_home_file\fP (\fBshfs_t\fP *fs, char *path)"
.br
.in -1c
.SH "Detailed Description"
.PP 
individual user 'home' file-system 
.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
