.TH "Libshare_fsbin" 3 "20 Mar 2015" "Version 2.24" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Libshare_fsbin \- 
.PP
libhshare filesystem inode binary I/O functionality.  

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBshfs_bin_read\fP (\fBshfs_ino_t\fP *file, \fBshbuf_t\fP *buff)"
.br
.RI "\fIRead binary content from a file. \fP"
.ti -1c
.RI "int \fBshfs_bin_write\fP (\fBshfs_ino_t\fP *file, \fBshbuf_t\fP *buff)"
.br
.RI "\fIWrite binary content to a file. \fP"
.in -1c
.SH "Detailed Description"
.PP 
libhshare filesystem inode binary I/O functionality. 
.SH "Function Documentation"
.PP 
.SS "int shfs_bin_read (\fBshfs_ino_t\fP * file, \fBshbuf_t\fP * buff)"
.PP
Read binary content from a file. 
.SS "int shfs_bin_write (\fBshfs_ino_t\fP * file, \fBshbuf_t\fP * buff)"
.PP
Write binary content to a file. 
.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
