.TH "Libshare_fszlib" 3 "20 Mar 2015" "Version 2.24" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Libshare_fszlib \- 
.PP
libshare filesystem inode compression I/O functionality  

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBshfs_zlib_read\fP (\fBshfs_ino_t\fP *file, \fBshbuf_t\fP *buff)"
.br
.ti -1c
.RI "int \fBshfs_zlib_write\fP (\fBshfs_ino_t\fP *file, \fBshbuf_t\fP *buff)"
.br
.in -1c
.SH "Detailed Description"
.PP 
libshare filesystem inode compression I/O functionality 
.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
