.TH "shdiff_options" 3 "20 Mar 2015" "Version 2.24" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shdiff_options \- 
.PP
Public: Options structure configures behavior of diff functions.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <shmem_diff_int.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBtimeout\fP"
.br
.ti -1c
.RI "int \fBedit_cost\fP"
.br
.ti -1c
.RI "float \fBmatch_threshold\fP"
.br
.ti -1c
.RI "float \fBmatch_distance\fP"
.br
.ti -1c
.RI "float \fBpatch_delete_threshold\fP"
.br
.ti -1c
.RI "int \fBpatch_margin\fP"
.br
.ti -1c
.RI "int \fBmatch_maxbits\fP"
.br
.ti -1c
.RI "int \fBcheck_lines\fP"
.br
.ti -1c
.RI "int \fBtrim_common_prefix\fP"
.br
.ti -1c
.RI "int \fBtrim_common_suffix\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Public: Options structure configures behavior of diff functions. 
.PP
Definition at line 20 of file shmem_diff_int.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
