.TH "shdiff_pool" 3 "20 Mar 2015" "Version 2.24" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shdiff_pool \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBshdiff_node\fP * \fBpool\fP"
.br
.ti -1c
.RI "uint32_t \fBpool_size\fP"
.br
.ti -1c
.RI "uint32_t \fBpool_used\fP"
.br
.ti -1c
.RI "shdiff_pos \fBfree_list\fP"
.br
.ti -1c
.RI "int \fBerror\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 43 of file shmem_diff_pool.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
