.TH "shfs_journal_data_t" 3 "25 Dec 2014" "Version 2.17" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shfs_journal_data_t \- 
.PP
A memory segment containing a journal's data.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <shfs.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBshfs_journal_block_t\fP \fBblock\fP [57344]"
.br
.RI "\fIThe journal's memory segment augmented into journal_blocks. \fP"
.in -1c
.SH "Detailed Description"
.PP 
A memory segment containing a journal's data. 
.PP
Definition at line 779 of file shfs.h.
.SH "Field Documentation"
.PP 
.SS "\fBshfs_journal_block_t\fP \fBshfs_journal_data_t::block\fP[57344]"
.PP
The journal's memory segment augmented into journal_blocks. 
.PP
Definition at line 783 of file shfs.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
