.TH "shfs_block_obj_t" 3 "20 Mar 2015" "Version 2.24" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shfs_block_obj_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBname\fP [((4096-sizeof(\fBshfs_hdr_t\fP))-34)]"
.br
.ti -1c
.RI "\fBshkey_t\fP \fBkey\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1627 of file shfs.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
