.TH "shmeta_entry_t" 3 "20 Mar 2015" "Version 2.24" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shmeta_entry_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBshmeta_entry_t\fP * \fBnext\fP"
.br
.ti -1c
.RI "unsigned int \fBhash\fP"
.br
.ti -1c
.RI "const void * \fBkey\fP"
.br
.ti -1c
.RI "ssize_t \fBklen\fP"
.br
.ti -1c
.RI "const void * \fBval\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 473 of file shmem.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
