.TH "shmsg_t" 3 "20 Mar 2015" "Version 2.24" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shmsg_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBshkey_t\fP \fBsrc_key\fP"
.br
.RI "\fIsource peer of message. \fP"
.ti -1c
.RI "\fBshkey_t\fP \fBdest_key\fP"
.br
.RI "\fIdestination peer of message. \fP"
.ti -1c
.RI "uint32_t \fBmsg_qid\fP"
.br
.RI "\fImessage queue id \fP"
.ti -1c
.RI "uint32_t \fBmsg_size\fP"
.br
.RI "\fItotal size of message content \fP"
.ti -1c
.RI "uint32_t \fBmsg_of\fP"
.br
.RI "\fIoffset of message data \fP"
.ti -1c
.RI "uint32_t \fB__reserved_1__\fP"
.br
.RI "\fItype of message \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 920 of file shfs.h.
.SH "Field Documentation"
.PP 
.SS "uint32_t \fBshmsg_t::__reserved_1__\fP"
.PP
type of message 
.PP
Definition at line 939 of file shfs.h.
.SS "\fBshkey_t\fP \fBshmsg_t::dest_key\fP"
.PP
destination peer of message. 
.PP
Definition at line 927 of file shfs.h.
.SS "uint32_t \fBshmsg_t::msg_of\fP"
.PP
offset of message data 
.PP
Definition at line 936 of file shfs.h.
.SS "uint32_t \fBshmsg_t::msg_qid\fP"
.PP
message queue id 
.PP
Definition at line 930 of file shfs.h.
.SS "uint32_t \fBshmsg_t::msg_size\fP"
.PP
total size of message content 
.PP
Definition at line 933 of file shfs.h.
.SS "\fBshkey_t\fP \fBshmsg_t::src_key\fP"
.PP
source peer of message. 
.PP
Definition at line 924 of file shfs.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
