.TH "shpeer_ipv6_t" 3 "26 Nov 2014" "Version 2.16" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shpeer_ipv6_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBshpeer_ipv6_addr_t\fP"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBsin6_family\fP"
.br
.ti -1c
.RI "uint16_t \fBsin6_port\fP"
.br
.ti -1c
.RI "uint32_t \fBsin6_flowinfo\fP"
.br
.ti -1c
.RI "struct \fBshpeer_ipv6_t::shpeer_ipv6_addr_t\fP \fBsin6_addr\fP"
.br
.ti -1c
.RI "uint32_t \fBsin6_scope_id\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 83 of file shpeer.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
