.TH "shpeer_key_t" 3 "20 Mar 2015" "Version 2.24" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shpeer_key_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBshkey_t\fP \fBpub\fP"
.br
.RI "\fIA key reference to the peer's public identity. \fP"
.ti -1c
.RI "\fBshkey_t\fP \fBpriv\fP"
.br
.RI "\fIA key reference to the peer's priveleged identity. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 99 of file shpeer.h.
.SH "Field Documentation"
.PP 
.SS "\fBshkey_t\fP \fBshpeer_key_t::priv\fP"
.PP
A key reference to the peer's priveleged identity. 
.PP
Definition at line 109 of file shpeer.h.
.SS "\fBshkey_t\fP \fBshpeer_key_t::pub\fP"
.PP
A key reference to the peer's public identity. 
.PP
Definition at line 104 of file shpeer.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
