.TH "shpool_t" 3 "20 Mar 2015" "Version 2.24" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shpool_t \- 
.PP
A memory pool.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <shmem.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBshbuf_t\fP ** \fBpool\fP"
.br
.ti -1c
.RI "int \fBmax\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A memory pool. 
.PP
Definition at line 336 of file shmem.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
