.TH "tx_account_msg_t" 3 "20 Mar 2015" "Version 2.24" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tx_account_msg_t \- 
.PP
Account information returned to a message-queue client.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <shnet.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBshseed_t\fP \fBpam_seed\fP"
.br
.ti -1c
.RI "uint32_t \fBpam_flag\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Account information returned to a message-queue client. 

\fBNote:\fP
.RS 4
This message is only sent from the client. 
.RE
.PP

.PP
Definition at line 194 of file shnet.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
