.TH "tx_license_msg_t" 3 "20 Mar 2015" "Version 2.24" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tx_license_msg_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBshpeer_t\fP \fBlic_peer\fP"
.br
.RI "\fIThe originating peer granting the license. \fP"
.ti -1c
.RI "\fBshsig_t\fP \fBlic_sig\fP"
.br
.RI "\fIThe digital signature the licence is granting access for. \fP"
.ti -1c
.RI "\fBshkey_t\fP \fBlic_name\fP"
.br
.RI "\fIThe key reference to the licensing content. \fP"
.ti -1c
.RI "\fBshtime_t\fP \fBlic_expire\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 215 of file shnet.h.
.SH "Field Documentation"
.PP 
.SS "\fBshkey_t\fP \fBtx_license_msg_t::lic_name\fP"
.PP
The key reference to the licensing content. 
.PP
Definition at line 221 of file shnet.h.
.SS "\fBshpeer_t\fP \fBtx_license_msg_t::lic_peer\fP"
.PP
The originating peer granting the license. 
.PP
Definition at line 217 of file shnet.h.
.SS "\fBshsig_t\fP \fBtx_license_msg_t::lic_sig\fP"
.PP
The digital signature the licence is granting access for. 
.PP
Definition at line 219 of file shnet.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
