/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.sharelib;

public class share_javaJNI {

  static {
    try {
      System.loadLibrary("share");
    } catch (UnsatisfiedLinkError e) {
      System.err.println("Native code library failed to load. \n" + e);
      System.exit(1);
    }
  }

  public final static native int test_main();
  public final static native String get_libshare_version();
  public final static native String get_libshare_title();
  public final static native String get_libshare_path();
  public final static native long shpeer();
  public final static native long ashpeer();
  public final static native void shpeer_free(long jarg1);
  public final static native void shpref_free();
  public final static native String shpref_get(String jarg1, String jarg2);
  public final static native int shpref_set(String jarg1, String jarg2);
  public final static native double shtimef(java.math.BigInteger jarg1);
  public final static native java.math.BigInteger shtime();
  public final static native java.math.BigInteger shtimeu(long jarg1);
  public final static native int shtimems(java.math.BigInteger jarg1);
  public final static native String shctime(java.math.BigInteger jarg1);
  public final static native long shutime(java.math.BigInteger jarg1);
  public final static native String shstrtime(java.math.BigInteger jarg1, String jarg2);
  public final static native java.math.BigInteger shtime_adj(java.math.BigInteger jarg1, double jarg2);
  public final static native java.math.BigInteger shgettime(long jarg1);
  public final static native int shtime_after(java.math.BigInteger jarg1, java.math.BigInteger jarg2);
  public final static native int shtime_before(java.math.BigInteger jarg1, java.math.BigInteger jarg2);
  public final static native double shtime_diff(java.math.BigInteger jarg1, java.math.BigInteger jarg2);
  public final static native void shbuf_append(long jarg1, long jarg2);
  public final static native long shbuf_clone(long jarg1);
  public final static native void shbuf_memcpy(long jarg1, byte[] jarg2);
  public final static native long shbuf_init();
  public final static native void shbuf_catstr(long jarg1, String jarg2);
  public final static native void shbuf_cat(long jarg1, byte[] jarg2);
  public final static native long shbuf_size(long jarg1);
  public final static native long shbuf_data(long jarg1);
  public final static native void shbuf_clear(long jarg1);
  public final static native void shbuf_trim(long jarg1, long jarg2);
  public final static native void shbuf_dealloc(long jarg1);
  public final static native void shbuf_truncate(long jarg1, long jarg2);
  public final static native java.math.BigInteger shcrc(byte[] jarg1);
  public final static native String shcrcstr(java.math.BigInteger jarg1);
  public final static native java.math.BigInteger shcrcgen(String jarg1);
  public final static native int shmsgget(long jarg1);
  public final static native int shmsgsnd(int jarg1, long jarg2, long jarg3);
  public final static native int shmsgrcv(int jarg1, long jarg2, long jarg3);
  public final static native int shmsgctl(int jarg1, int jarg2, int jarg3);
  public final static native String shfs_app_name(String jarg1);
  public final static native java.math.BigInteger shfs_crc(long jarg1);
  public final static native long shfs_size(long jarg1);
  public final static native long shfs_init(long jarg1);
  public final static native void shfs_free(long jarg1);
  public final static native long shfs_dir_base(long jarg1);
  public final static native long shfs_dir_parent(long jarg1);
  public final static native long shfs_dir_entry(long jarg1, String jarg2);
  public final static native long shfs_dir_find(long jarg1, String jarg2);
  public final static native String shfs_meta_get(long jarg1, String jarg2);
  public final static native int shfs_meta_perm(long jarg1, String jarg2, long jarg3);
  public final static native int shfs_meta_set(long jarg1, String jarg2, String jarg3);
  public final static native int shfs_read_mem(String jarg1, long jarg2, long jarg3);
  public final static native int shfs_write_mem(String jarg1, byte[] jarg2);
  public final static native long shfs_file_find(long jarg1, String jarg2);
  public final static native int shfs_file_pipe(long jarg1, int jarg2);
  public final static native void sherr(int jarg1, String jarg2);
  public final static native void shwarn(String jarg1);
  public final static native void shinfo(String jarg1);
  public final static native int shnet_accept(int jarg1);
  public final static native int shnet_bindsk(int jarg1, String jarg2, long jarg3);
  public final static native int shnet_bind(int jarg1, long jarg2, long jarg3);
  public final static native int shclose(int jarg1);
  public final static native int shnet_fcntl(int jarg1, int jarg2, int jarg3);
  public final static native int shconnect_host(String jarg1, int jarg2, int jarg3);
  public final static native long shresolve(String jarg1);
  public final static native long shaddr(int jarg1);
  public final static native String shaddr_print(long jarg1);
  public final static native long shnet_read(int jarg1, long jarg2, long jarg3);
  public final static native int shnet_sk();
  public final static native int shnet_socket(int jarg1, int jarg2, int jarg3);
  public final static native long shnet_write(int jarg1, long jarg2, long jarg3);
  public final static native int shnet_verify(long jarg1, long jarg2, long jarg3);
  public final static native long shkey_bin(String jarg1, long jarg2);
  public final static native long shkey_str(String jarg1);
  public final static native long shkey_num(int jarg1);
  public final static native long shkey_uniq();
  public final static native void shkey_free(long jarg1);
  public final static native String shkey_print(long jarg1);
  public final static native long ashkey_str(String jarg1);
  public final static native long ashkey_num(int jarg1);
  public final static native int shkey_cmp(long jarg1, long jarg2);
  public final static native long shkey_clone(long jarg1);
  public final static native long shkey_cert(long jarg1, java.math.BigInteger jarg2, java.math.BigInteger jarg3);
  public final static native int shkey_verify(long jarg1, java.math.BigInteger jarg2, long jarg3, java.math.BigInteger jarg4);
  public final static native long shkey_gen(String jarg1);
  public final static native long shpool_init();
  public final static native long shpool_size(long jarg1);
  public final static native void shpool_grow(long jarg1);
  public final static native long shpool_get(long jarg1, long jarg2);
  public final static native long shpool_get_index(long jarg1, int jarg2);
  public final static native void shpool_put(long jarg1, long jarg2);
  public final static native void shpool_free(long jarg1);
  public final static native int ashencode(String jarg1, long jarg2, long jarg3);
  public final static native int shencode(String jarg1, long jarg2, long jarg3, long jarg4, long jarg5);
  public final static native long shencode_str(String jarg1);
  public final static native int ashdecode(long jarg1, long jarg2, long jarg3);
  public final static native int shdecode(long jarg1, long jarg2, long jarg3, long jarg4, long jarg5);
  public final static native int shdecode_str(String jarg1, long jarg2);
  public final static native long shlock_open(long jarg1, int jarg2);
  public final static native int shlock_tryopen(long jarg1, int jarg2, long jarg3);
  public final static native int shlock_close(long jarg1);
  public final static native void sh_sha256(long jarg1, long jarg2, long jarg3);
  public final static native String shdigest(long jarg1, int jarg2);
  public final static native String shjson_print(long jarg1);
  public final static native String shjson_str(long jarg1, String jarg2, String jarg3);
  public final static native String shjson_astr(long jarg1, String jarg2, String jarg3);
  public final static native long shjson_str_add(long jarg1, String jarg2, String jarg3);
  public final static native void shjson_free(long jarg1);
  public final static native double shjson_num(long jarg1, String jarg2, double jarg3);
  public final static native long shjson_num_add(long jarg1, String jarg2, double jarg3);
  public final static native long shjson_init(String jarg1);
  public final static native long shjson_array_add(long jarg1, String jarg2);
  public final static native String shjson_array_str(long jarg1, String jarg2, int jarg3);
  public final static native String shjson_array_astr(long jarg1, String jarg2, int jarg3);
  public final static native double shjson_array_num(long jarg1, String jarg2, int jarg3);
  public final static native long shjson_obj(long jarg1, String jarg2);
  public final static native long shjson_strlen(long jarg1, String jarg2);
  public final static native long shfs_inode(long jarg1, String jarg2, int jarg3);
  public final static native String shfs_filename(long jarg1);
  public final static native int shfs_type(long jarg1);
  public final static native long shfs_inode_parent(long jarg1);
  public final static native long shfs_inode_load(long jarg1, long jarg2);
}
