/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.sharelib;

public class SWIGTYPE_p_fd_set {
  private long swigCPtr;

  protected SWIGTYPE_p_fd_set(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_fd_set() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_fd_set obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

