.TH "intro" 3 "25 Jan 2015" "Version 2.22" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
intro \- Introduction 
This documentation covers the public API provided by the Share library.
.PP
The documentation is for developers of 3rd-party applications intending to use this API.
.PP
The following modules are available:
.IP "\(bu" 2
\fBThe sharefs filesystem\fP
.IP "\(bu" 2
\fBNetworking and the ESP protocol.\fP
.IP "\(bu" 2
\fBHashmaps and memory pools.\fP
.IP "\(bu" 2
\fBLibrary Configuration\fP 
.PP

