.TH "Libshare_fsobj" 3 "8 May 2015" "Version 2.26" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Libshare_fsobj \- 
.PP
generic object key references  

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBshfs_block_obj_t\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBshfs_block_obj_t\fP \fBshfs_block_obj_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBshfs_obj_set\fP (\fBshfs_ino_t\fP *file, char *name, \fBshkey_t\fP *key)"
.br
.ti -1c
.RI "int \fBshfs_obj_get\fP (\fBshfs_ino_t\fP *file, char *name, \fBshkey_t\fP **key_p)"
.br
.in -1c
.SH "Detailed Description"
.PP 
generic object key references 
.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
