.TH "Libshare_memdelta" 3 "8 May 2015" "Version 2.26" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Libshare_memdelta \- 
.PP
Generate xd3 diff comparisons.  

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBshdelta\fP (\fBshbuf_t\fP *src_buff, \fBshbuf_t\fP *in_buff, \fBshbuf_t\fP *out_buff)"
.br
.ti -1c
.RI "int \fBshpatch\fP (\fBshbuf_t\fP *src_buff, \fBshbuf_t\fP *in_buff, \fBshbuf_t\fP *out_buff)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Generate xd3 diff comparisons. 
.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
