.TH "Libshare_sys" 3 "8 May 2015" "Version 2.26" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Libshare_sys \- 
.PP
System-level routines.  

.SS "Modules"

.in +1c
.ti -1c
.RI "\fBLibshare_syspam\fP"
.br
.PP

.RI "\fIPermission access management. \fP"
.ti -1c
.RI "\fBLibshare_sysshadow\fP"
.br
.PP

.RI "\fIShadow password file management. \fP"
.ti -1c
.RI "\fBLibshare_sysapp\fP"
.br
.PP

.RI "\fIApplication state management. \fP"
.ti -1c
.RI "\fBLibshare_syscrypt\fP"
.br
.PP

.RI "\fIPerform posix crypt algorythm for sha256, and sha512. \fP"
.ti -1c
.RI "\fBLibshare_fslog\fP"
.br
.PP

.RI "\fIApplication logging calls. \fP"
.ti -1c
.RI "\fBLibshare_sysmsg\fP"
.br
.PP

.RI "\fIlibshare IPC message-queue IO calls. \fP"
.ti -1c
.RI "\fBLibshare_sysproc\fP"
.br
.PP

.RI "\fIlibshare spawned process management \fP"
.in -1c
.SH "Detailed Description"
.PP 
System-level routines. 
.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
