.TH "scrypt_peer" 3 "8 May 2015" "Version 2.26" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scrypt_peer \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBnonce1\fP [16]"
.br
.ti -1c
.RI "size_t \fBn1_len\fP"
.br
.ti -1c
.RI "size_t \fBn2_len\fP"
.br
.ti -1c
.RI "double \fBdiff\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1185 of file shmem.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
