.TH "sh_sha512_t" 3 "8 May 2015" "Version 2.26" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sh_sha512_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint64_t \fBtotal\fP [2]"
.br
.ti -1c
.RI "uint64_t \fBstate\fP [8]"
.br
.ti -1c
.RI "unsigned char \fBbuffer\fP [128]"
.br
.ti -1c
.RI "unsigned char \fBipad\fP [128]"
.br
.ti -1c
.RI "unsigned char \fBopad\fP [128]"
.br
.ti -1c
.RI "int \fBis384\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1288 of file shmem.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
