.TH "shbuf_t" 3 "8 May 2015" "Version 2.26" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shbuf_t \- 
.PP
A memory buffer that utilizes that re-uses available memory to reduce OS overhead and dynamically grows to a user specific need.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <shmem.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned char * \fBdata\fP"
.br
.ti -1c
.RI "size_t \fBdata_of\fP"
.br
.ti -1c
.RI "size_t \fBdata_max\fP"
.br
.ti -1c
.RI "size_t \fBdata_pos\fP"
.br
.ti -1c
.RI "int \fBfd\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A memory buffer that utilizes that re-uses available memory to reduce OS overhead and dynamically grows to a user specific need. 

\fBSee also:\fP
.RS 4
\fBshbuf_init\fP \fBshbuf_free\fP 
.RE
.PP

.PP
\fBExamples: \fP
.in +1c
.PP
\fBshkeystore.c\fP.
.PP
Definition at line 84 of file shmem.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
