.TH "shdiff_node" 3 "8 May 2015" "Version 2.26" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shdiff_node \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const char * \fBtext\fP"
.br
.ti -1c
.RI "uint32_t \fBlen\fP"
.br
.ti -1c
.RI "int \fBop\fP"
.br
.ti -1c
.RI "shdiff_pos \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 32 of file shmem_diff_pool.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
