.TH "shfile_t" 3 "18 Nov 2014" "Version 2.16" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shfile_t \- 
.PP
A reference to a local file-system path.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <shfile.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBsize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A reference to a local file-system path. 
.PP
Definition at line 50 of file shfile.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
