.TH "shfs_block_access" 3 "10 Jan 2015" "Version 2.19" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shfs_block_access \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBshkey_t\fP \fBacc_owner\fP"
.br
.ti -1c
.RI "\fBshpeer_t\fP \fBacc_group\fP"
.br
.ti -1c
.RI "\fBshkey_t\fP \fBacc_ward\fP"
.br
.ti -1c
.RI "uint32_t \fBacc_mask\fP"
.br
.ti -1c
.RI "\fBshkey_t\fP \fBlk_owner\fP"
.br
.ti -1c
.RI "uint32_t \fBlk_mask\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 391 of file shfs.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
