.TH "shfs_ino_buf" 3 "8 May 2015" "Version 2.26" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shfs_ino_buf \- 
.PP
The current stream positioned when stream-based I/O is performed.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <shfs.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBshbuf_t\fP * \fBbuff\fP"
.br
.RI "\fIbuffered data segment of inode data \fP"
.ti -1c
.RI "off_t \fBbuff_of\fP"
.br
.RI "\fIoffset for data segment from beginning inode data \fP"
.ti -1c
.RI "off_t \fBbuff_pos\fP"
.br
.RI "\fIcurrent IO read/write index position of data segment (buff). \fP"
.ti -1c
.RI "size_t \fBbuff_max\fP"
.br
.RI "\fIcurrent limit of stream size \fP"
.ti -1c
.RI "int \fBflags\fP"
.br
.RI "\fIfile stream state modifiers \fP"
.in -1c
.SH "Detailed Description"
.PP 
The current stream positioned when stream-based I/O is performed. 

\fBSee also:\fP
.RS 4
\fBshfopen()\fP 
.RE
.PP

.PP
Definition at line 495 of file shfs.h.
.SH "Field Documentation"
.PP 
.SS "\fBshbuf_t\fP* \fBshfs_ino_buf::buff\fP"
.PP
buffered data segment of inode data 
.PP
Definition at line 498 of file shfs.h.
.SS "size_t \fBshfs_ino_buf::buff_max\fP"
.PP
current limit of stream size 
.PP
Definition at line 504 of file shfs.h.
.SS "off_t \fBshfs_ino_buf::buff_of\fP"
.PP
offset for data segment from beginning inode data 
.PP
Definition at line 500 of file shfs.h.
.SS "off_t \fBshfs_ino_buf::buff_pos\fP"
.PP
current IO read/write index position of data segment (buff). 
.PP
Definition at line 502 of file shfs.h.
.SS "int \fBshfs_ino_buf::flags\fP"
.PP
file stream state modifiers 
.PP
Definition at line 506 of file shfs.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
