.TH "shfs_idx_t" 3 "8 May 2015" "Version 2.26" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shfs_idx_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBshfs_inode_off_t\fP \fBjno\fP"
.br
.RI "\fIThe journal number where the inode presides. \fP"
.ti -1c
.RI "\fBshfs_inode_off_t\fP \fBino\fP"
.br
.RI "\fIAn inode index in journal to initial data block. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 359 of file shfs.h.
.SH "Field Documentation"
.PP 
.SS "\fBshfs_inode_off_t\fP \fBshfs_idx_t::ino\fP"
.PP
An inode index in journal to initial data block. 
.PP
Definition at line 370 of file shfs.h.
.SS "\fBshfs_inode_off_t\fP \fBshfs_idx_t::jno\fP"
.PP
The journal number where the inode presides. 
.PP
Definition at line 365 of file shfs.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
