.TH "shfs_rev_t" 3 "1 Jan 2015" "Version 2.18" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shfs_rev_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint64_t \fBrev_crc\fP"
.br
.RI "\fIdata content checksum \fP"
.ti -1c
.RI "\fBshkey_t\fP \fBrev_inode\fP"
.br
.RI "\fIname key of revision inode. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1519 of file shfs.h.
.SH "Field Documentation"
.PP 
.SS "uint64_t \fBshfs_rev_t::rev_crc\fP"
.PP
data content checksum 
.PP
Definition at line 1522 of file shfs.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
