.TH "shfs_ref_t" 3 "10 Jan 2015" "Version 2.19" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shfs_ref_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBref_ver\fP"
.br
.ti -1c
.RI "uint16_t \fB_reserved_\fP"
.br
.ti -1c
.RI "\fBshfs_idx_t\fP \fBref_pos\fP"
.br
.ti -1c
.RI "\fBshpeer_t\fP \fBref_peer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1515 of file shfs.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
