.TH "shpeer_ipv6_t::shpeer_ipv6_addr_t" 3 "26 Nov 2014" "Version 2.16" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shpeer_ipv6_t::shpeer_ipv6_addr_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBnet6_addr\fP [4]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 87 of file shpeer.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
