.TH "shproc_req_t" 3 "8 May 2015" "Version 2.26" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shproc_req_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBstate\fP"
.br
.ti -1c
.RI "uint32_t \fBerror\fP"
.br
.ti -1c
.RI "uint32_t \fBcrc\fP"
.br
.ti -1c
.RI "uint32_t \fBdata_len\fP"
.br
.ti -1c
.RI "uint32_t \fBuser_fd\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 449 of file shsys.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
