.TH "shproc_t" 3 "8 May 2015" "Version 2.26" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shproc_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBshproc_stat_t\fP"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBproc_pid\fP"
.br
.ti -1c
.RI "int \fBproc_state\fP"
.br
.ti -1c
.RI "int \fBproc_fd\fP"
.br
.ti -1c
.RI "int \fBproc_idx\fP"
.br
.ti -1c
.RI "int \fBproc_error\fP"
.br
.ti -1c
.RI "int \fBproc_prio\fP"
.br
.ti -1c
.RI "int \fBuser_fd\fP"
.br
.ti -1c
.RI "int \fBdgram_fd\fP"
.br
.ti -1c
.RI "shproc_op_t \fBproc_req\fP"
.br
.ti -1c
.RI "shproc_op_t \fBproc_resp\fP"
.br
.ti -1c
.RI "\fBshtime_t\fP \fBproc_stamp\fP"
.br
.ti -1c
.RI "\fBshbuf_t\fP * \fBproc_buff\fP"
.br
.ti -1c
.RI "struct \fBshproc_t::shproc_stat_t\fP \fBstat\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 459 of file shsys.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
