.TH "shproc_t::shproc_stat_t" 3 "8 May 2015" "Version 2.26" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shproc_t::shproc_stat_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBin_tot\fP"
.br
.ti -1c
.RI "int \fBout_tot\fP"
.br
.ti -1c
.RI "double \fBspan_tot\fP [4]"
.br
.ti -1c
.RI "int \fBspan_cnt\fP [4]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 476 of file shsys.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
