.TH "shproc_pool_t" 3 "8 May 2015" "Version 2.26" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shproc_pool_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBpool_max\fP"
.br
.ti -1c
.RI "int \fBpool_lim\fP"
.br
.ti -1c
.RI "int \fBpool_prio\fP"
.br
.ti -1c
.RI "shproc_op_t \fBpool_req\fP"
.br
.ti -1c
.RI "shproc_op_t \fBpool_resp\fP"
.br
.ti -1c
.RI "\fBshproc_t\fP * \fBproc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 486 of file shsys.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
