.TH "shseed_t" 3 "8 May 2015" "Version 2.26" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shseed_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBshkey_t\fP \fBseed_key\fP"
.br
.ti -1c
.RI "\fBshkey_t\fP \fBseed_sig\fP"
.br
.ti -1c
.RI "\fBshtime_t\fP \fBseed_stamp\fP"
.br
.ti -1c
.RI "uint64_t \fBseed_salt\fP"
.br
.ti -1c
.RI "uint64_t \fBseed_uid\fP"
.br
.ti -1c
.RI "uint32_t \fBseed_type\fP"
.br
.ti -1c
.RI "uint32_t \fB_reserved_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1379 of file shmem.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
