.TH "shsig_t" 3 "8 May 2015" "Version 2.26" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shsig_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBshkey_t\fP \fBsig_id\fP"
.br
.ti -1c
.RI "\fBshkey_t\fP \fBsig_peer\fP"
.br
.ti -1c
.RI "\fBshkey_t\fP \fBsig_key\fP"
.br
.ti -1c
.RI "\fBshtime_t\fP \fBsig_stamp\fP"
.br
.ti -1c
.RI "\fBshtime_t\fP \fBsig_expire\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 847 of file shfs.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
