.TH "tx_bond_msg_t" 3 "8 May 2015" "Version 2.26" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tx_bond_msg_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBbond_sink\fP [136]"
.br
.ti -1c
.RI "char \fBbond_label\fP [136]"
.br
.ti -1c
.RI "\fBshsig_t\fP \fBbond_sig\fP"
.br
.ti -1c
.RI "\fBshtime_t\fP \fBbond_expire\fP"
.br
.ti -1c
.RI "uint64_t \fBbond_credit\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 241 of file shnet.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
