.TH "tx_event_msg_t" 3 "8 May 2015" "Version 2.26" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tx_event_msg_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBshpeer_t\fP \fBevent_peer\fP"
.br
.ti -1c
.RI "\fBshsig_t\fP \fBevent_sig\fP"
.br
.ti -1c
.RI "\fBshtime_t\fP \fBevent_stamp\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 235 of file shnet.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
