.TH "tx_id_msg_t" 3 "8 May 2015" "Version 2.26" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tx_id_msg_t \- 
.PP
Account identity returned to a message-queue client.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <shnet.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBshpeer_t\fP \fBid_peer\fP"
.br
.ti -1c
.RI "\fBshkey_t\fP \fBid_key\fP"
.br
.ti -1c
.RI "\fBshtime_t\fP \fBid_stamp\fP"
.br
.ti -1c
.RI "uint64_t \fBid_uid\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Account identity returned to a message-queue client. 

\fBNote:\fP
.RS 4
This message is only sent from the server. Typical use is auxillary applications authorizating actions in an IPC manner. Use the 'shinfo' share utility program to display active \fIshare identity\fP instances. 
.RE
.PP

.PP
Definition at line 212 of file shnet.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
